### PR TITLE
integration with Composer

### PR DESCRIPTION
**Pull request by roxblnfk**
You can also complete the field "required" with a string
``` "skrol/tinybutstrong": "dev-master" ```

### CODE REVIEW

**Comment by Skrol29** [comment]
Thanks,
But doesn't should the « composer.json » file mention the dependency with TinyButStrong ?

**Comment by simonschaufi** [comment]
`dev-master` won't work for releases. You need to add a git tag version like `"^v1.0.0"` (required to have a git tag available with `v1.0.0` already.

**Comment by roxblnfk** [comment]
> You need to add a git tag version

It would be very useful to add tags with version numbers

**Comment by roxblnfk** [comment]
First do merge https://github.com/Skrol29/tinybutstrong/pull/3
- Then merge this pull request
- add tag with latest version
- and do register in  packagist.org

**Comment by Skrol29** [comment]
Hi, can you explain why a gitignore with "/composer.lock" and "/vendor/µ" ?

**Comment by roxblnfk** [comment]
> Hi, can you explain why a gitignore with "/composer.lock" and "/vendor/*" ?

https://getcomposer.org/doc/02-libraries.md#lock-file
https://blog.martinhujer.cz/17-tips-for-using-composer-efficiently/ <= Tip 6

About vendor: this folder may appear during development (with tinybutstrong) and should not be sent to git

**Comment by simonschaufi** [comment]
Please leave it like before. it was correct. the lock file should only be added on projects but not on libraries.

**Pull request merged**
